---

- name: create docker-sd configuration directory
  ansible.builtin.file:
    path: "{{ docker_sd_config_dir }}"
    state: directory
    owner: root
    group: "{{ docker_sd_system_group }}"
    mode: 0770

- name: create docker-sd configuration
  ansible.builtin.template:
    src: "docker-sd/config.yml.j2"
    dest: "{{ docker_sd_config_dir }}/docker-sd.yml"
    force: true
    owner: root
    group: "{{ docker_sd_system_group }}"
    mode: 0640
  notify:
    - restart docker-sd

...
