---

namespace: bodsch
name: prometheus

version: 0.12.0

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: A collection of Ansible roles for the Prometheus universe.

license:
  - Apache-2.0

license_file: ''

tags:
  - monitoring
  - prometheus
  - exporters

dependencies:
  bodsch.core: ">=1.1.2"
  bodsch.scm: "*"

repository: https://github.com/bodsch/ansible-collection-prometheus
documentation: https://github.com/bodsch/ansible-collection-prometheus/README.md
homepage: https://github.com/bodsch/ansible-collection-prometheus
issues: https://github.com/bodsch/ansible-collection-prometheus/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
