---

prometheus_service:
  log:
    level: info
  web:
    listen_address: "0.0.0.0:9090"

prometheus_global:
  scrape_interval: 5m
  evaluation_interval: 2m
  external_labels:
    environment: MOLECULE
    production: not

prometheus_alerting:
  alert_relabel_configs: []
  alertmanagers: []

prometheus_file_sd_targets:
  #
  node:
    - targets:
        - localhost:9100
      labels:
        env: test
  sensors:
    - labels:
        service: sensors
      targets:
        - sensor-01.matrix.lan:9080  # buero
        - sensor-02.matrix.lan:9080  # titus
        - sensor-03.matrix.lan:9080  # esszimmer
        # - sensor-04.matrix.lan:9080@wohnzimmer
        - sensor-05.matrix.lan:9080    # it-raum
        # - sensor-06.matrix.lan:9080@kueche
        # - sensor-07.matrix.lan:9080@bad
  kresd:
    - labels:
        service: dns
      targets:
        - ns.matrix.lan:8453
#  node:
#    - targets:
#        - localhost:9100
#      labels:
#        env: test

#prometheus_rule_files:
#  - "foo.yml"
#  - bar.json
prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  #
  - job_name: grafana
    static_configs:
      - targets:
          - 127.0.0.1:3000
  #
  - job_name: node
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
          # - "{{ prometheus_config_dir }}/file_sd/node2.yml"
        refresh_interval: 2m

  # sensors
  - job_name: sensors
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/sensors.yml"
    relabel_configs:
      # remove port from instance name
      - source_labels:
          - __address__
        regex: (.*):.*
        replacement: $1
        target_label: instance
      # Extract the host ID (last octet of IPv4 address)
      - source_labels:
          - __address__
        regex: "sensor-(\\d+)..*"
        target_label: host_id
      # Set location label
      - source_labels:
          - host_id
        regex: "01"
        replacement: buero
        target_label: location
      # Set location label
      - source_labels:
          - host_id
        regex: "01"
        replacement: buero
        target_label: location
      - source_labels:
          - host_id
        regex: "02"
        replacement: titus
        target_label: location
      - source_labels:
          - host_id
        regex: "03"
        replacement: esszimmer
        target_label: location

      - source_labels:
          - host_id
        regex: "05"
        replacement: it-bunker
        target_label: location
  #
  - job_name: kresd
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/kresd.yml"



...
