---

- name: checksum
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: get checksum list
      bodsch.scm.github_checksum:
        project: prometheus
        repository: node_exporter
        checksum_file: sha256sums.txt
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        architecture: "{{ ansible_architecture }}"
        system: "{{ ansible_facts.system }}"
        version: "v{{ node_exporter_version }}"
      register: _latest_checksum

    - name: define checksum for {{ go_arch }} architecture
      ansible.builtin.set_fact:
        __node_exporter_checksums: "{{ _latest_checksum.checksum }}"
      when:
        - _latest_checksum.rc == 0
        - _latest_checksum.checksum is defined
        - _latest_checksum.checksum | string | length > 0

# - name: define checksum
#   become: false
#   delegate_to: localhost
#   run_once: true
#   block:
#     - name: get checksum list
#       ansible.builtin.set_fact:
#         __node_exporter_checksums: "{{ lookup('url', 'https://github.com/prometheus/node_exporter/releases/download/v' + node_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
#
#     - name: get checksum for {{ go_arch }} architecture
#       ansible.builtin.set_fact:
#         __node_exporter_checksums: "{{ __node_exporter_checksums | node_exporter_checksum('linux', go_arch) }}"

- name: download node_exporter binary archive
  become: false
  delegate_to: "{{ node_exporter_delegate_to }}"
  run_once: "{{ 'false' if node_exporter_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ node_exporter_release_download_url }}/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ node_exporter_local_tmp_directory }}/node_exporter-linux-amd64.tar.gz"
    checksum: "sha256:{{ __node_exporter_checksums }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract node_exporter archive
  become: false
  delegate_to: "{{ node_exporter_delegate_to }}"
  run_once: "{{ 'false' if node_exporter_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ node_exporter_local_tmp_directory }}/node_exporter-linux-amd64.tar.gz"
    dest: "{{ node_exporter_local_tmp_directory }}"
    copy: false
  register: _extract_archive

...
